# -*- coding: utf-8 -*-
"""calculadora.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qP1BMlllLffg8wadhX4QegWerT9Ogw4r
"""

print("Calculadora Simples")

# Solicita os números e a operação ao usuário
num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
operacao = input("Escolha a operação (+, -, *, /): ")

# Realiza a operação escolhida
if operacao == '+':
    resultado = num1 + num2
elif operacao == '-':
    resultado = num1 - num2
elif operacao == '*':
    resultado = num1 * num2
elif operacao == '/':
    if num2 == 0:
        print("Erro: Divisão por zero!")
        exit(1)
    resultado = num1 / num2
else:
    print("Operação Inválida!")
    exit(1)

# Exibe o resultado
print(f"O resultado é: {resultado}")